# -*- coding: utf-8 -*-
"""Bản sao của Colaboratory chào mừng bạn!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u00fUGEo_2C23c38Bm2ZCxEfsjTw4n5Q
"""

import seaborn as sns
from google.colab import files
uploaded=files.upload()

import pandas as pd
import io
housing=pd.read_excel(io.BytesIO(uploaded["AmesHousing.xls"]) )
numerical=['SalePrice', 'Lot Area','Overall Qual','Overall Cond','2nd Flr SF', '1st Flr SF', 'Bedroom AbvGr']
categorical=['MS Zoning','Lot Shape','Neighborhood', 'Central Air', 'Sale Condition','Mo Sold','Yr Sold']
housing=housing[numerical+categorical]
housing.info()

import seaborn as sns
sns.set(style='whitegrid', palette='deep', font_scale=1.1, rc={'figure.figsize':[8,5]})
sns.distplot(housing['SalePrice'], norm_hist=False, kde=False, bins=20,
hist_kws={'alpha':1}).set(xlabel='Sale Price', ylabel='Count')

housing[numerical].hist(bins=15, figsize=(15,6), layout=(2,4))

sns.countplot(housing['Sale Condition'])

import matplotlib.pyplot as plt
fig, ax = plt.subplots(2, 4, figsize=(20, 10)) 
for variable, subplot in zip(categorical, ax.flatten()):
  sns.countplot(housing[variable], ax=subplot) 
  for label in subplot.get_xticklabels():
      label.set_rotation(90)

sns.scatterplot(x=housing['1st Flr SF'], y=housing['SalePrice']);

sns.jointplot(x=housing['1st Flr SF'], y=housing['SalePrice']);

fig, ax = plt.subplots(3, 3, figsize=(15, 10))
for var, subplot in zip(categorical, ax.flatten()):
  sns.boxplot(x=var, y='SalePrice', data=housing, ax=subplot)

sorted_nb = housing.groupby(['Neighborhood'])['SalePrice'].median().sort_values()
sns.boxplot(x=housing['Neighborhood'], y=housing['SalePrice'], order=list(sorted_nb.index))